### ISSUE TITLE
linting script doesn't work

### ISSUE THREAD

**Issue by m4v15** [FACK1/fid-sh-had-week8#10]
Hi,

Just had a look and the path for your `lint` script is wrong:

https://github.com/FACK1/fid-sh-had-week8/blob/0019475f64bf9e3a8caa51d2e9f1bae2c65fb424/package.json#L9

I think you don't want to go into the server folder?

Also eslint won't work without a config file.

I suggest on a new branch quickly:

1. change your lint script path
2. run `eslint --init` and choose the airbnb style guide
3. run `npm run lint` to see lint problems
4. run`npm run lint-fix` and manually fix any other problems
5. put in a PR and get it merged ASAP

**Comment by Hadeel-Salamin** [comment]
got fixed @m4v15
