### ISSUE TITLE
Endpoints

### ISSUE THREAD

**Issue by Hadeel-Salamin** [FACK1/fid-sh-had-week8#4]
- [x] Home page  ```GET /``` 
    - Response should render html home page
- [x] Search function ```GET /search``` 
    - Get data by search value from request 
    - Call ```getData()``` query from database folder 
    -  Response should be rendering result to search.hbs file 
    - Data should be manipulate inside search.hbs file 
- [x] Login function ```POST /login```
   - Get username and password from request
    - Call ```getUser()``` query from database 
    - Validate if username and password already exists 
    - SetCookies for the user
    - Response should be redirect to profile.hbs
 - [x] Add Tutorials ```POST /addTutorials```
     -Get ```username value``` , ```language name value``` , ```link value``` from request
     -Post ```username``` , ```language name``` , ```link``` by addData() query to database
- [x] signup function ```POST /signup```
   - Get username, email and password from request
    - Call ```postUser()``` query from database 
    - Validate if username and password already exists, if not add user
    - Response should be redirect to home.hbs
- [x] Handle errors 
  - page not found if status code = 404
  - server error if status code = 500

**Comment by m4v15** [comment]
LOVE THIS 😍
